SELECT * FROM train


SELECT COUNT(*) FROM train

SELECT * FROM train
WHERE STORE IS NULL
OR DEPT IS NULL
OR DATE IS NULL 
OR WEEKLY_SALES IS NULL 
OR ISHOLÝDAY IS NULL

SELECT DATE , SUM(WEEKLY_SALES) AS TOTALSUM FROM train
GROUP BY DATE
ORDER BY TOTALSUM DESC

SELECT ISHOLÝDAY , SUM(Weekly_Sales) AS TOTALSUMHOLÝDAY FROM train
GROUP BY IsHoliday
ORDER BY TOTALSUMHOLÝDAY DESC

SELECT MAX(Weekly_Sales) AS  WEEKLY_SALESMAX  , MIN(WEEKLY_SALES) AS  WEEKLY_SALESMIN FROM train


SELECT STORE , SUM(WEEKLY_SALES) AS TOTALSALES FROM train
GROUP BY STORE

SELECT STORE, MAX(WEEKLY_SALES) AS MAXPRÝCE FROM train
GROUP BY STORE

SELECT STORE , MIN(WEEKLY_SALES) AS MINPRICE FROM train
GROUP BY Store

SELECT STORE ,SUM(WEEKLY_SALES) AS WEEKSALES FROM train
GROUP BY Store
ORDER BY WEEKSALES DESC



SELECT  MIN(Store) AS STORE , MIN(DEPT) AS DEPT , MIN(Weekly_Sales) AS WEEKSALES FROM train

SELECT  MAX(STORE) AS STORE, MAX(DEPT) AS DEPT , MAX(WEEKLY_SALES) AS WEEKSALES FROM train

SELECT DATE , SUM(WEEKLY_SALES) AS TOTALSUM  FROM train
WHERE DATE BETWEEN  '2010-01-01' AND '2010-12-31'
GROUP BY DATE
ORDER BY DATE ASC

 
 SELECT DATE , SUM(WEEKLY_SALES) AS TOTALSUM FROM train
 WHERE Date  BETWEEN '2011-01-01'  AND '2011-12-31'
 GROUP BY DATE
 ORDER BY DATE ASC

 SELECT DATE , SUM(WEEKLY_SALES) AS TOTALSUM FROM train
 WHERE DATE BETWEEN '2012-01-01' AND '2012-12-31'
 GROUP BY DATE 
 ORDER  BY DATE ASC





